### ISSUE TITLE
Add something about open() and \r\n and \n

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/cours-python#1]
See doc Python 2 vs Python 3:

https://docs.python.org/2.7/library/functions.html#open

**Comment by pierrepo** [comment]
https://docs.python.org/3.6/library/functions.html#open

**Comment by patrickfuchs** [comment]
Voir open() @ https://docs.python.org/3.6/library/functions.html#open

**Comment by patrickfuchs** [comment]
Haha, tu l'avais déjà mis :-D !!!

**Comment by patrickfuchs** [comment]
Mini topo sur \r\n et la fonction open() ajouté dans le chap 7 sur la lecture de fichier.
