### ISSUE TITLE
Ajouter un mot sur les fonctions récursives dans cha 19

### ISSUE THREAD

**Issue by patrickfuchs** [pierrepo/cours-python#18]
TODO !

**Comment by pierrepo** [comment]
à mettre plutôt dans le chapitre 12 avec un cours exemple. Voir issue #28

**Comment by patrickfuchs** [comment]
Problème, j'ai peur que ça embrouille les débutants... Ou alors on dit aux débutants de sauter ça ?

**Comment by pierrepo** [comment]
Oui, mais avec le factoriel, c'est compréhensible je trouve.

**Comment by patrickfuchs** [comment]
Réglé dans l'issue #28.
