### ISSUE TITLE
chapitre 12 : ajouter exemple fonction récursive

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/cours-python#28]
A la fin de la section *Appel d'une fonction dans une fonction*, montrer un exemple de fonction récursive. 

L'exemple classique de Fibonacci : 

```
def F(n):
    if n == 0: 
    	return 0
    elif n == 1: 
    	return 1
    else: 
    	return F(n-1)+F(n-2)
```

**Comment by patrickfuchs** [comment]
Sinon je trouve qu'il y a plus simple, c'est le factoriel :

    def calc_factorielle(nb):
        if nb == 0:
            return 1
        else:
            return nb * factorielle(nb - 1)

A tester en pythontutor, c'est vraiment trop beau :-D !!!

**Comment by pierrepo** [comment]
Je suis d'accord, c'est beaucoup plus simple :+1:

**Comment by patrickfuchs** [comment]
C'est fait, il reste juste une bricole avec un lien à régler !
