### ISSUE TITLE
Mettre au format code dans une puce

### ISSUE THREAD

**Issue by patrickfuchs** [pierrepo/cours-python#3]
Dans le chap 5, je suis tombé sur un os en Markdown (pour l'instant j'ai écrit @@@ HELP @@@ pour que tu trouves l'endroit. Je suis à l'intérieur d'une puce, et je souhaite mettre dans cet élément de la puce un fragment de code :

---------------------------
- BLABLABLABLA

     ici j'indente
     et je voudrais écrire 
     au format code

---------------------------

Or le fragment indenté ne veut pas se mettre en code car au-dessus on est dans une puce. Sais-tu comment faire ça ?

**Comment by pierrepo** [comment]
Hello @patrickfuchs ,

il faut alors indenter deux fois (mais avec 6 espace seuleument au lieu de 8). Exemple : 

Test en dehors d'une puce.

    Code en dehors d'une puce.
    Encore du code.

- Première puce.
    Text dans la première puce.

      Code dans la première puce
      Encore du code.

- Seconde puce.
 
      Code dans la seconde puce.
      Encore du code.        

Texte en dehors de la puce.

Voici le même exemple sur [Monod](https://monod.lelab.tailordev.fr/28771b52-f927-4323-9911-b05b87c7dfe3#sD9rpM56c+09GClTMJu88Yj5QALAhukx2BHBtd808To=)

**Comment by patrickfuchs** [comment]
OK merci.
