### ISSUE TITLE
Projet : mots anglais/français dans le protéome humain

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/cours-python#38]
Projet amusant : trouver les mots anglais/français qui se retrouve dans le protéome humain (dans les séquences).

Liste de mots en anglais et français : dans `/usr/share/dict`

Protéome humain (~20 000 séquences) : http://www.uniprot.org/help/human_proteome

- ne prendre que les mots de plus de 3 ? 4 ? caractères
- pour les mots français, supprimer les accents

**Comment by patrickfuchs** [comment]
Très bonne idée :-)

**Comment by pierrepo** [comment]
done.
