### ISSUE TITLE
Chap 5 fichiers / manipulation de deux fichiers avec with

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/cours-python#9]
Donner un exemple de la manipulation simultanée de deux fichiers avec `with`. Par exemple : 

    with open('zoo.txt', 'r') as fichier1, open('zoo2.txt', 'w') as fichier2:
        for ligne in fichier1:
            fichier2.write('* ' + ligne)

Si le contenu de `zoo.txt` est : 

    souris
    girafe
    lion
    singe

alors celui de `zoo2.txt` sera : 

    * souris
    * girafe
    * lion
    * singe

**Comment by patrickfuchs** [comment]
Done
